# Generated by Django 3.1.1 on 2021-12-07 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20211205_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTracker',
            fields=[
                ('id', models.CharField(default=project_tracker.models.project_tracker_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('excavation', models.CharField(max_length=5)),
                ('foundation', models.CharField(max_length=5)),
                ('plinth_stage', models.CharField(max_length=5)),
                ('gf_brick_work', models.CharField(max_length=5)),
                ('gf_slab', models.CharField(max_length=5)),
                ('first_floor_brick_work', models.CharField(max_length=5)),
                ('first_slab', models.CharField(max_length=5)),
                ('electrical_works', models.CharField(max_length=5)),
                ('plumbing_works', models.CharField(max_length=5)),
                ('wood_grill_works', models.CharField(max_length=5)),
                ('internal_plastering', models.CharField(max_length=5)),
                ('external_plastering', models.CharField(max_length=5)),
                ('flooring_tiling', models.CharField(max_length=5)),
                ('painting', models.CharField(max_length=5)),
                ('finishing', models.CharField(max_length=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecttracker', to='accounts.projectdetails')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
