# Generated by Django 3.1.1 on 2021-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttracker',
            name='electrical_works',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='excavation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='external_plastering',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='finishing',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='first_floor_brick_work',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='first_slab',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='flooring_tiling',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='foundation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='gf_brick_work',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='gf_slab',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='internal_plastering',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='painting',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='plinth_stage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='plumbing_works',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='wood_grill_works',
            field=models.FloatField(),
        ),
    ]
