# Generated by Django 3.2.9 on 2021-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_description',
            field=models.TextField(max_length=1000),
        ),
    ]
