# Generated by Django 3.2.9 on 2021-11-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20211123_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDrawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_schedule', models.CharField(max_length=100)),
                ('joinery_details', models.CharField(max_length=200)),
                ('plumbing_details', models.CharField(max_length=200)),
                ('electrical', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('section_elevation', models.CharField(max_length=100)),
                ('toilet_detailing', models.CharField(max_length=100)),
                ('brick_work_layout', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_drawings', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_d_elevation', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='StructuralDrawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_line_plan', models.CharField(max_length=200)),
                ('footing_layout', models.CharField(max_length=200)),
                ('column_details', models.CharField(max_length=200)),
                ('plinth_beam_details', models.CharField(max_length=200)),
                ('beam_layout', models.CharField(max_length=100)),
                ('beam_details', models.CharField(max_length=200)),
                ('slab_details', models.CharField(max_length=200)),
                ('staircase_details', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_drawings', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq', models.CharField(max_length=100)),
                ('payments', models.BooleanField()),
                ('projects_schedule', models.CharField(max_length=100)),
                ('quality_checkList', models.CharField(max_length=100)),
                ('specifications', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_plans', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_plans', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_agreements', models.CharField(max_length=100)),
                ('main_agreements', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='accounts.projectdetails')),
            ],
        ),
    ]
