# Generated by Django 3.1.1 on 2021-12-02 08:06

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDrawings',
            fields=[
                ('id', models.IntegerField(default=documents.models.working_drawings_generate_id, editable=False, primary_key=True, serialize=False)),
                ('open_schedule', models.ImageField(upload_to='image/')),
                ('joinery_details', models.ImageField(upload_to='image/')),
                ('plumbing_details', models.ImageField(upload_to='image/')),
                ('electrical', models.ImageField(upload_to='image/')),
                ('section', models.ImageField(upload_to='image/')),
                ('section_elevation', models.ImageField(upload_to='image/')),
                ('toilet_detailing', models.ImageField(upload_to='image/')),
                ('brick_work_layout', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workingdrawings', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeD',
            fields=[
                ('id', models.IntegerField(default=documents.models.three_generate_id, editable=False, primary_key=True, serialize=False)),
                ('three_d_elevation', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='StructuralDrawings',
            fields=[
                ('id', models.IntegerField(default=documents.models.structural_drawing_generate_id, editable=False, primary_key=True, serialize=False)),
                ('center_line_plan', models.ImageField(upload_to='image/')),
                ('footing_layout', models.ImageField(upload_to='image/')),
                ('column_details', models.ImageField(upload_to='image/')),
                ('plinth_beam_details', models.ImageField(upload_to='image/')),
                ('beam_layout', models.ImageField(upload_to='image/')),
                ('beam_details', models.ImageField(upload_to='image/')),
                ('slab_details', models.ImageField(upload_to='image/')),
                ('staircase_details', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_drawings', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.IntegerField(default=documents.models.document_generate_id, editable=False, primary_key=True, serialize=False)),
                ('boq', models.ImageField(upload_to='image/')),
                ('payments', models.ImageField(upload_to='image/')),
                ('projects_schedule', models.ImageField(upload_to='image/')),
                ('quality_checkList', models.ImageField(upload_to='image/')),
                ('specifications', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptPlans',
            fields=[
                ('id', models.IntegerField(default=documents.models.concept_plan_generate_id, editable=False, primary_key=True, serialize=False)),
                ('concept_plans', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_plans', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.IntegerField(default=documents.models.agreement_generate_id, editable=False, primary_key=True, serialize=False)),
                ('booking_agreements', models.ImageField(upload_to='image/')),
                ('main_agreements', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='accounts.projectdetails')),
            ],
        ),
    ]
