# Generated by Django 3.1.1 on 2021-12-04 06:25

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDrawings',
            fields=[
                ('id', models.CharField(default=accounts.models.personal_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('open_schedule', models.ImageField(upload_to='image/')),
                ('joinery_details', models.ImageField(upload_to='image/')),
                ('plumbing_details', models.ImageField(upload_to='image/')),
                ('electrical', models.ImageField(upload_to='image/')),
                ('section', models.ImageField(upload_to='image/')),
                ('section_elevation', models.ImageField(upload_to='image/')),
                ('toilet_detailing', models.ImageField(upload_to='image/')),
                ('brick_work_layout', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workingdrawings', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeD',
            fields=[
                ('id', models.CharField(default=accounts.models.personal_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('three_d_elevation', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='StructuralDrawings',
            fields=[
                ('id', models.CharField(default=accounts.models.personal_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('center_line_plan', models.ImageField(upload_to='image/')),
                ('footing_layout', models.ImageField(upload_to='image/')),
                ('column_details', models.ImageField(upload_to='image/')),
                ('plinth_beam_details', models.ImageField(upload_to='image/')),
                ('beam_layout', models.ImageField(upload_to='image/')),
                ('beam_details', models.ImageField(upload_to='image/')),
                ('slab_details', models.ImageField(upload_to='image/')),
                ('staircase_details', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_drawings', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.CharField(default=accounts.models.personal_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('inside', models.ImageField(upload_to='inside/')),
                ('outside', models.ImageField(upload_to='outside/')),
                ('two_d_image', models.ImageField(upload_to='two_d/')),
                ('three_d_image', models.ImageField(upload_to='three_d/')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.CharField(default=accounts.models.personal_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('boq', models.ImageField(upload_to='image/')),
                ('payments', models.ImageField(upload_to='image/')),
                ('projects_schedule', models.ImageField(upload_to='image/')),
                ('quality_checkList', models.ImageField(upload_to='image/')),
                ('specifications', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptPlans',
            fields=[
                ('id', models.CharField(default=accounts.models.personal_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('concept_plans', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_plans', to='accounts.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.CharField(default=accounts.models.personal_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('booking_agreements', models.ImageField(upload_to='image/')),
                ('main_agreements', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='accounts.projectdetails')),
            ],
        ),
    ]
