# Generated by Django 3.2.9 on 2021-11-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211123_1335'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='booking_agreements',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='main_agreements',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='conceptplans',
            name='concept_plans',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='boq',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='payments',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='projects_schedule',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='quality_checkList',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='specifications',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='beam_details',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='beam_layout',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='center_line_plan',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='column_details',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='footing_layout',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='plinth_beam_details',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='slab_details',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='staircase_details',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='brick_work_layout',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='electrical',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='joinery_details',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='open_schedule',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='plumbing_details',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='project_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workingdrawings', to='accounts.projectdetails'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='section',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='section_elevation',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='toilet_detailing',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
