# Generated by Django 3.2.9 on 2021-12-05 07:18

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211205_1248'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeD1',
            fields=[
                ('id', models.CharField(default=accounts.models.personal_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('three_d_elevation', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='accounts.projectdetails')),
            ],
        ),
    ]
