# Generated by Django 3.2.9 on 2021-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_threed1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='main_agreements',
            field=models.ImageField(upload_to='image2/'),
        ),
        migrations.DeleteModel(
            name='ThreeD1',
        ),
    ]
