# Generated by Django 3.2.9 on 2021-12-05 07:48

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20211205_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='id',
            field=models.CharField(default=documents.models.agreement_generate_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='main_agreements',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='conceptplans',
            name='id',
            field=models.CharField(default=documents.models.concept_plan_generate_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='id',
            field=models.CharField(default=documents.models.document_generate_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='id',
            field=models.CharField(default=documents.models.gallery_generate_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='structuraldrawings',
            name='id',
            field=models.CharField(default=documents.models.structural_drawing_generate_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workingdrawings',
            name='id',
            field=models.CharField(default=documents.models.working_drawings_generate_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
