# Generated by Django 3.1.1 on 2021-12-05 08:28

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211205_1248'),
        ('documents', '0004_auto_20211205_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insideimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outsideimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='threed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.CharField(default=documents.models.three_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('three_d_elevation', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d', to='accounts.projectdetails')),
            ],
        ),
    ]
