# Generated by Django 3.2.9 on 2021-12-05 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTracker',
            fields=[
                ('id', models.CharField(default=payment_tracker.models.payment_tracker_generate_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('total_project_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
