# Generated by Django 3.2.9 on 2021-12-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
