# Generated by Django 3.1.1 on 2021-12-10 12:29

import department.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCoordination',
            fields=[
                ('emp_name', models.CharField(max_length=25)),
                ('emp_id', models.CharField(default=department.models.project_coordination_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_coordination', to='accounts.projectdetails')),
            ],
            options={
                'verbose_name_plural': 'Project Coordination',
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('emp_name', models.CharField(max_length=25)),
                ('emp_id', models.CharField(default=department.models.generate_finance_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='accounts.projectdetails')),
            ],
            options={
                'verbose_name_plural': 'Finance',
            },
        ),
        migrations.CreateModel(
            name='ExecutionTeam',
            fields=[
                ('emp_name', models.CharField(max_length=25)),
                ('emp_id', models.CharField(default=department.models.execution_team_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_team', to='accounts.projectdetails')),
            ],
            options={
                'verbose_name_plural': 'Execution Team',
            },
        ),
        migrations.CreateModel(
            name='DesignTeam',
            fields=[
                ('emp_name', models.CharField(max_length=25)),
                ('emp_id', models.CharField(default=department.models.design_team_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_team', to='accounts.projectdetails')),
            ],
            options={
                'verbose_name_plural': 'Design Team',
            },
        ),
    ]
